language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
env:
  global:
    # AWS_S3_MAX_AGE_SECONDS
    - AWS_S3_MAX_AGE_SECONDS=36000
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - travis_retry pip install -r tests/requirements.txt --download-cache $HOME/.pip-cache
  - pip install -e . --download-cache $HOME/.pip-cache
script:
  - coverage run tests/manage.py test django_s3_storage
after_script:
  - coverage report
notifications:
  email: false
