language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
env:
  global:
    # AWS_REGION
    - secure: "xPckDCfsKYH2ZPttPg7XCDIhWKT5Wut5tysuthLTMuYqygD5WiTCkEZSHoH8oFdXJOFmO5bIDx1bZ/A7qFUeVnNouqIN71qHRObYwv3JgPbQC0lFRYs1OaGlTV4g8pJanqgx/gWF4ztaRLWdYCMK/yNPr5sju/NYlUUpA6XHQumQeZpu1dfzut6syoLyyKgyhqVUEmfKFHTTP25pXOKlHgM267Kmlm6aTljdPiWqyDTxGZmeABth5y1zHmND9cZumKBU56AdCBxuAdkXd50qFCGDHYTvx3hRw8DOQIVEScX3PqCLUknxipP7WKKoXZOKXM8qb9S37HBcqbEIeQ/YzqAaRm7fmBoFRx9KyEE/tCmG6X55U2BZyawYw+Z33BI+GKH7M593Rw8jfHctG+EQUVoIQbNzOvMivtmKVMvm4ICLHy9pXvViH7QiPH8joEFQHz9GjkYl79wAIRkZqcFN4WyhUeY+4QylMvZePO21+/azOLiWXo1U8KtPSvc/bhsYrg1m703Sh+LMSRQykQxYQPREnd86nX461X1PkEARST6LrkJbM/tOmwS8OXR43vgxN/Kn6tBoLI4fBnDZtkxusGEOKnjXBt5FgpeSHjUVss6erXXqsMZnA+o/Irjr/we1DipRYMS25EpxDalZlKWTsAeGtKXjFx3Ds1iRcLSVkUY="
    # AWS_ACCESS_KEY_ID
    - secure: "TlE5Y/rdY8wz6kpAELWtgS7MBRmEXkch0t/+3XLdVDWpu7nLP4BcKbDt4m53/QFHiPGvm82VycOMAHIllEgbeX9xabgUj+/d/1zgkA/5JhYYXbPjNk3Hnt8o/oT20cJPpCBj3OfFXyxEGUYnOpqahXBblIf7EAAojP2Bh0/nNu6BvOWDRdYujB40U5Av5MgH+EnPKZ7PMyQCh9D1ABTrO0Zf7LyrGvWl/GE6xA7xS3M0N73D+xvOzpACeJL5/nalPysFaCIHTsKcmGQ/Zlq4dy/SDdNlx/Jb0W9AZ2QhYbY2u4cadHxDNlNYemKlKr/8srK9lxcDKIACh5n9ei7cG6WkXKi3q0xl6tA03kXinrcakuou3BIYahJO8GH5l46zX3HQlhBF4bzL+RL6IcxoIkMMA9WCDw6NrGiudNHarAI6zjt1Uw7/HQUx2R87uK2+gwZxvBEvqTYoPGo2AHwLGy6NzsUXJi7SWeJ7fOt39EI9ExSwf9a7UYiQxRuPIrL0jUpCIcLSvgDg3Z49sKHFe+tVQOQ7BQvkUZejjyp43YRYQSXCe1FReJ3g49dlhbYUrA6x1LBRcOaRkel/gDn2otaHkWm0UrvjcreCESPUm0C8ak/ognLJ/7ogKMGkKKgd5OAjLrwvtL1Bu6BE1FS6dl4sE5wphpb5dcCbVAqkcbk="
   # AWS_SECRET_ACCESS_KEY
    - secure: "w9lJfRHTQZVNhY4UEs5gyDFYkNT8ZAIWi3xaKGJM1Esy4X9Ws0Hg58UYXoZyvh/7CbFi91dKpEyUotjHD7xcejGpP7awFVUQSuu87C6UAb4uRr4VVmZ/MW65shpybR6tUwSFtRKln/O+zWmvsaVn9alyQGnJY7H64n55U9zqqFh52fsfTBN3AHiyZccIAsf6iccCGcdSmTOXbLFSGNFC2uH1Ta11h4EWO1vc+hFS1wR6RqMClqbJjzo2CK7S6onIKM6FTIpaGHaV1kuD7b8jmkKzsvBcLesOHumI9Ts8FfZXxSq0MOYg9EJ4JxHxOpkxpnTQ0S1FCNGPYFr3d/Tu0UkzAuE/WxIRmr0R5kR90doL6yNfEIfueU2QVCn9zdk1bw3jzgvQYtio/wMNWOOt7flnC5NoDTv/tk9iebuIVucjNIF/C6DBQ9Gz3eI/H4lZDAaNQ47lLJkGj4WpuRAkFHCgVWz5clCeEAkldtnIQR7orxE53pZCo4AtnNvi1hHnTe3YMSz4CwtoNuocj89cMK8mWkHov7pRszYgEaIKsAmVJnDRYg3vGuUBIksRoJkVXwkC56kMaLHE3s1lOjYjq74mcftBeK9I/4p20wIFEcvo/rhSjvm+bB4t2hhx8CGLd9equQ3NJusk6nZD++7hAKuE6KlY4ii2dLosXxrG8g8="
    # AWS_S3_BUCKET_NAME
    - secure: "Hz+qdLUSH/9hUwASdL0WTBjo3o88LObtQ4E8v23yKEy93cEFPfAhvYj6a2uZfK6xlkTBDQU6Crm5aDkh0zxuq8qxzE10XdDfQ3YIRVAMKzJhNfKQTa2PLBdxOoRIGwTlz+J6w5G+antImWxfD3X0z2YxCUnZBBqxDJPnkLuKmVslyGOx/QaQ9hVTB0dRqFZmobFGVAorU0h82YMmhoyoUHgtFdbBZIDSxezExJ3gfoxKAwB3wYxWh+GleV2NzXMJaECux4VKKM0dZmcK3V4syqMiOO8HcReR02YX40FF0B633BjiETabN5DAPYvO0+70pnXogi6cIX/Qayf8m4XsdVz+snTs8qk934YxsWYdsyR8jr2tSBaMfOkk0uXnMHDgMvj7kwTWbRBrAxH4FNi6qKUaWr99BM/90Csx64Z4ux3unG6RJlArs24c1/orrBdxtiXgLmj6iRSdrJzr6YQnwOhGl3NvvdmvNqhfvZcef3fTxCjBYScHbWP5LvAUVPj+TmoPsS/BwuwhfO1ctCOaR7qtvxM5UWmWDOmKaXmSTPhl2sa5HVT0sJofD5AYypWzxJoxSvQQ18fR4aGGTXIWrWf7eduiRtl4leAUXJWg90v5Tcp//BUgilIwDyahvm+hjjRqwzj9Wki6ESIo3QUnBu0LmQXpvJWvMAY6+sytUv8="
    # AWS_S3_BUCKET_NAME_STATIC
    - secure: "Hz+qdLUSH/9hUwASdL0WTBjo3o88LObtQ4E8v23yKEy93cEFPfAhvYj6a2uZfK6xlkTBDQU6Crm5aDkh0zxuq8qxzE10XdDfQ3YIRVAMKzJhNfKQTa2PLBdxOoRIGwTlz+J6w5G+antImWxfD3X0z2YxCUnZBBqxDJPnkLuKmVslyGOx/QaQ9hVTB0dRqFZmobFGVAorU0h82YMmhoyoUHgtFdbBZIDSxezExJ3gfoxKAwB3wYxWh+GleV2NzXMJaECux4VKKM0dZmcK3V4syqMiOO8HcReR02YX40FF0B633BjiETabN5DAPYvO0+70pnXogi6cIX/Qayf8m4XsdVz+snTs8qk934YxsWYdsyR8jr2tSBaMfOkk0uXnMHDgMvj7kwTWbRBrAxH4FNi6qKUaWr99BM/90Csx64Z4ux3unG6RJlArs24c1/orrBdxtiXgLmj6iRSdrJzr6YQnwOhGl3NvvdmvNqhfvZcef3fTxCjBYScHbWP5LvAUVPj+TmoPsS/BwuwhfO1ctCOaR7qtvxM5UWmWDOmKaXmSTPhl2sa5HVT0sJofD5AYypWzxJoxSvQQ18fR4aGGTXIWrWf7eduiRtl4leAUXJWg90v5Tcp//BUgilIwDyahvm+hjjRqwzj9Wki6ESIo3QUnBu0LmQXpvJWvMAY6+sytUv8="
    # AWS_S3_MAX_AGE_SECONDS
    - AWS_S3_MAX_AGE_SECONDS=3600
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - travis_retry pip install -r tests/requirements.txt --download-cache $HOME/.pip-cache
  - pip install -e . --download-cache $HOME/.pip-cache
script:
  - coverage run tests/manage.py test django_s3_storage
after_script:
  - coverage report
notifications:
  email: false
